version: '3'

vars:
  BRAIN_PORT: '{{.BRAIN_PORT | default "8765"}}'
  BRAIN_HOST: '{{.BRAIN_HOST | default "localhost"}}'
  BRAIN_URL: 'ws://{{.BRAIN_HOST}}:{{.BRAIN_PORT}}/aria'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # BUILD
  build:
    desc: Build both brain and body in release mode
    deps: [build-brain, build-body]

  build-brain:
    desc: Build the brain (substrate)
    dir: aria-brain
    cmds:
      - cargo build --release

  build-body:
    desc: Build the body (interface)
    dir: aria-body
    cmds:
      - cargo build --release

  # RUN
  brain:
    desc: Start the brain (run this first)
    dir: aria-brain
    env:
      ARIA_PORT: '{{.BRAIN_PORT}}'
    cmds:
      - cargo run --release

  body:
    desc: Start the body interface
    dir: aria-body
    env:
      ARIA_BRAIN_URL: '{{.BRAIN_URL}}'
    cmds:
      - cargo run --release

  body-visual:
    desc: Start the body in visual TUI mode
    dir: aria-body
    env:
      ARIA_BRAIN_URL: '{{.BRAIN_URL}}'
    cmds:
      - cargo run --release -- --visual

  # TESTING
  test:
    desc: Run all tests
    cmds:
      - cd aria-brain && cargo test
      - cd aria-body && cargo test

  check:
    desc: Check code without building
    cmds:
      - cd aria-brain && cargo check
      - cd aria-body && cargo check

  fmt:
    desc: Format all code
    cmds:
      - cd aria-brain && cargo fmt
      - cd aria-body && cargo fmt

  # MONITORING
  health:
    desc: Check if brain is running
    cmds:
      - curl -s http://{{.BRAIN_HOST}}:{{.BRAIN_PORT}}/health

  stats:
    desc: Get brain statistics
    cmds:
      - curl -s http://{{.BRAIN_HOST}}:{{.BRAIN_PORT}}/stats | jq .

  words:
    desc: Show words ARIA has learned
    cmds:
      - curl -s http://{{.BRAIN_HOST}}:{{.BRAIN_PORT}}/words | jq .

  words-familiar:
    desc: Show only familiar words (heard 5+ times)
    cmds:
      - curl -s http://{{.BRAIN_HOST}}:{{.BRAIN_PORT}}/words | jq '.words | map(select(.count >= 5))'

  associations:
    desc: Show semantic word associations
    cmds:
      - curl -s http://{{.BRAIN_HOST}}:{{.BRAIN_PORT}}/associations | jq .

  # DATA MANAGEMENT
  reset:
    desc: Reset ARIA memory (start fresh)
    cmds:
      - rm -f aria-brain/data/aria.memory
      - echo "Memory cleared"

  backup:
    desc: Backup ARIA memory
    cmds:
      - mkdir -p backups
      - cp aria-brain/data/aria.memory backups/aria.memory.$(date +%Y%m%d_%H%M%S) 2>/dev/null || echo "No memory yet"

  # REMOTE (PC Gamer)
  body-remote:
    desc: Connect body to remote brain (PC Gamer)
    dir: aria-body
    vars:
      REMOTE_HOST: '{{.REMOTE_HOST | default "192.168.1.35"}}'
    env:
      ARIA_BRAIN_URL: 'ws://{{.REMOTE_HOST}}:{{.BRAIN_PORT}}/aria'
    cmds:
      - echo "Connecting to brain at ws://{{.REMOTE_HOST}}:{{.BRAIN_PORT}}/aria"
      - cargo run --release

  stats-remote:
    desc: Get stats from remote brain
    vars:
      REMOTE_HOST: '{{.REMOTE_HOST | default "192.168.1.35"}}'
    cmds:
      - curl -s http://{{.REMOTE_HOST}}:{{.BRAIN_PORT}}/stats | jq .

  words-remote:
    desc: Get words from remote brain
    vars:
      REMOTE_HOST: '{{.REMOTE_HOST | default "192.168.1.35"}}'
    cmds:
      - curl -s http://{{.REMOTE_HOST}}:{{.BRAIN_PORT}}/words | jq .

  health-remote:
    desc: Check if remote brain is running
    vars:
      REMOTE_HOST: '{{.REMOTE_HOST | default "192.168.1.35"}}'
    cmds:
      - curl -s http://{{.REMOTE_HOST}}:{{.BRAIN_PORT}}/health | jq .

  # QUICK START
  start:
    desc: Build and start brain in background, then body
    cmds:
      - task build
      - echo "Starting brain..."
      - cd aria-brain && cargo run --release &
      - sleep 3
      - task health
      - echo "Starting body..."
      - task body

  stop:
    desc: Stop all ARIA processes
    cmds:
      - pkill -f aria-brain || true
      - pkill -f aria-body || true
      - echo "ARIA stopped"
